apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: esps0pgml-python
  janus-idp.io/tekton: esps0pgml-python
  backstage.io/kubernetes-id: esps0pgml-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: esps0pgml-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
