apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: esps0pgml-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: esps0pgml-python 
  name: esps0pgml-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: esps0pgml-python 
